# Generated by Django 5.0.6 on 2024-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_userlocale_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocale',
            name='federation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
